locations = ['china', 'france', 'rome', 'georgia', 'scotland']
print(locations)
print(sorted(locations))
print(locations)
loc = sorted(locations, reverse=True)
print(loc)
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)